<?php require __DIR__.'/config/bootstrap.php'; $title=setting('site_name','PlayGramBlog'); require __DIR__.'/includes/header.php';
$featured=db()->query("SELECT p.*,c.name category,u.name author FROM posts p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.author_id WHERE p.status='published' AND p.published_at<=NOW() ORDER BY p.is_featured DESC,p.published_at DESC LIMIT 1")->fetch();
$latest=db()->query("SELECT p.*,c.name category,u.name author FROM posts p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.author_id WHERE p.status='published' AND p.published_at<=NOW() ORDER BY p.published_at DESC LIMIT 9")->fetchAll();
?>
<?php if($featured): ?><section class="hero"><div class="meta"><?=e($featured['category'])?> · <?=e($featured['author'])?></div><h1><?=e($featured['title'])?></h1><p><?=e(excerpt($featured['content']))?></p><a class="btn" href="post.php?slug=<?=e($featured['slug'])?>">Read article →</a></section><?php endif; ?>
<section class="section"><h2>Latest Articles</h2><div class="grid"><?php foreach($latest as $p): ?><article class="card"><img loading="lazy" src="<?=e($p['featured_image']?:'assets/images/placeholder.svg')?>" alt="<?=e($p['title'])?>"><div class="pad"><div class="meta"><?=e($p['category'])?> · <?=date('M j, Y',strtotime($p['published_at']))?></div><h3><a href="post.php?slug=<?=e($p['slug'])?>"><?=e($p['title'])?></a></h3><p><?=e(excerpt($p['content']))?></p><span class="meta"><?=reading_time($p['content'])?> min read · <?=number_format((int)$p['view_count'])?> views</span></div></article><?php endforeach; ?></div></section>
<?php $cats=db()->query("SELECT c.*,COUNT(p.id) posts FROM categories c LEFT JOIN posts p ON p.category_id=c.id AND p.status='published' GROUP BY c.id ORDER BY c.name")->fetchAll(); ?>
<section class="section"><h2>Categories</h2><div class="grid"><?php foreach($cats as $c): ?><div class="card"><div class="pad"><h3><a href="category.php?slug=<?=e($c['slug'])?>"><?=e($c['name'])?></a></h3><p><?=e($c['description'])?></p><span class="meta"><?=e($c['posts'])?> posts</span></div></div><?php endforeach; ?></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
