CREATE DATABASE IF NOT EXISTS playgramblog CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE playgramblog;
CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,
 role ENUM('super_admin','admin','editor','author','user') NOT NULL DEFAULT 'user',status ENUM('active','inactive','banned') NOT NULL DEFAULT 'active',
 avatar VARCHAR(500) NULL,bio TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(role),INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,description TEXT, image VARCHAR(500),
 seo_title VARCHAR(255),seo_description TEXT,status TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tags (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,slug VARCHAR(140) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS posts (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(255) NOT NULL UNIQUE,excerpt TEXT,content LONGTEXT NOT NULL,featured_image VARCHAR(500),
 category_id INT UNSIGNED NULL,author_id INT UNSIGNED NOT NULL,status ENUM('draft','published','scheduled') NOT NULL DEFAULT 'draft',
 is_featured TINYINT(1) NOT NULL DEFAULT 0,published_at DATETIME NULL,view_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
 seo_title VARCHAR(255),seo_description TEXT,seo_keywords TEXT,canonical_url VARCHAR(500),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(status,published_at),INDEX(category_id),INDEX(author_id),FULLTEXT(title,content),
 FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL,FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS post_tags(post_id INT UNSIGNED NOT NULL,tag_id INT UNSIGNED NOT NULL,PRIMARY KEY(post_id,tag_id),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS comments(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id INT UNSIGNED NOT NULL,name VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL,comment TEXT NOT NULL,
 status ENUM('pending','approved','rejected','spam') NOT NULL DEFAULT 'pending',ip_address VARCHAR(45),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(post_id,status),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS pages(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(255) NOT NULL UNIQUE,content LONGTEXT NOT NULL,status ENUM('draft','published') DEFAULT 'published',
 seo_title VARCHAR(255),seo_description TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS media(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,filename VARCHAR(255) NOT NULL UNIQUE,original_name VARCHAR(255),mime_type VARCHAR(100),size_bytes BIGINT UNSIGNED,url VARCHAR(500),user_id INT UNSIGNED,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS subscribers(email VARCHAR(190) PRIMARY KEY,status ENUM('active','unsubscribed') DEFAULT 'active',subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contact_messages(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,subject VARCHAR(255) NOT NULL,message TEXT NOT NULL,status ENUM('unread','read') DEFAULT 'unread',ip_address VARCHAR(45),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS advertisements(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,ad_code TEXT NOT NULL,placement ENUM('header','homepage','sidebar','between_posts','article_content','footer') NOT NULL,status TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings(setting_key VARCHAR(100) PRIMARY KEY,setting_value LONGTEXT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS menus(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS menu_items(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,menu_id INT UNSIGNED NOT NULL,parent_id INT UNSIGNED NULL,label VARCHAR(150) NOT NULL,url VARCHAR(500) NOT NULL,sort_order INT DEFAULT 0,status TINYINT(1) DEFAULT 1,FOREIGN KEY(menu_id) REFERENCES menus(id) ON DELETE CASCADE,FOREIGN KEY(parent_id) REFERENCES menu_items(id) ON DELETE SET NULL,INDEX(menu_id,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS post_views(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id INT UNSIGNED NOT NULL,ip_address VARCHAR(45),user_agent VARCHAR(255),viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(post_id,viewed_at),INDEX(ip_address,viewed_at),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190),ip_address VARCHAR(45),attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(email,attempted_at),INDEX(ip_address,attempted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notifications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED,message TEXT,is_read TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS activity_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NULL,action VARCHAR(100) NOT NULL,entity VARCHAR(100),entity_id INT UNSIGNED,ip_address VARCHAR(45),user_agent VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(created_at),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO categories(name,slug,description) VALUES ('Technology','technology','Technology, software and the web'),('Gaming','gaming','Games and gaming culture'),('Tutorials','tutorials','Practical guides and tutorials');
INSERT IGNORE INTO pages(title,slug,content,status) VALUES
('About','about','<p>Welcome to PlayGramBlog.</p>','published'),
('Privacy Policy','privacy-policy','<p>We respect your privacy. Configure this page from the admin panel.</p>','published'),
('Terms & Conditions','terms','<p>Use of this site is subject to these terms.</p>','published'),
('Disclaimer','disclaimer','<p>Content is provided for general information.</p>','published');
